spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yandex
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
bot:
  name: GetToWorkInTimeBot
  token: 7881959830:AAEMtPX1qXapq1bY7Jn6XXFX_rlowQ2EMc4
dadata:
  api:
    key: "079ab8ffc4cc858af3494978f47b670e5f5aa516"
    secret: "7552d9b3d2427f38c46e09aca23633e161a39a60"
TwoGis:
  api:
    key: "ece4c580-4d99-4ef9-a32b-167db93a33a3"